### PR TITLE
feat(source-facebook-marketing): added fivetran dbt converter 

### LINKED ISSUE #10: Create dbt converter for Airbyte Facebook Marketing source connector
The goal of this task is to ensure the Airbyte Facebook Ads connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/facebook/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

### PR DESCRIPTION
**Pull request by FloDevelops**
resolves #10 

✅ I moved the logic as much upstream as I could as seen in other issues, reducing the complexity.

⚠️ I likely have rare Postgresql syntax to wrap around a new macro to extract sublevel json text for BQ and SF.

Just want to make sure I am in the right direction and almost ready to merge.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @FloDevelops I'm gonna review tomorrow and give feedback about the contribution. It looks Facebook uses the union macro to query staging tables.

**Comment by FloDevelops** [comment]
@marcosmarxm correct!
Fivetran's staging/source package unions multiple sources into temporary models.
These temporary models are then used to create the staging models.

To minimize the conversion while keeping the most functionalities, I rebuilt the temporary models with Airbyte sources.
This way, I am still using Fivetran's staging and analytical models.

**Comment by FloDevelops** [comment]
@marcosmarxm just added the /vars file for the CI

**Review by marcosmarxm — APPROVED** [review]
There are small details but the model looks good. Thanks @FloDevelops

**Pull request merged**
