### PR TITLE
Source Intercom : Add DBT converter

### LINKED ISSUE #15: Create dbt converter for Airbyte Intercom source connector
The goal of this task is to ensure the Airbyte Intercom connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/intercom/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

### PR DESCRIPTION
**Pull request by nthapa000**
Fixes #15

### CODE REVIEW

**Comment by nthapa000** [comment]
Hey @marcosmarxm 
1) I want you to pay close attention to what I've mentioned inside parenthesis for the some fields in the columns of 
`Table No.s: 3,6,10 and 13`.

2) Conversions for `Table Number 7 and 8` are yet to added. The `assignee` object is present in `conversations.yaml` but I could not find it in the `api documentation`.

In the next comment I will post the column match data for the tables

p.s. : Does the PR look good?

Thank You 🙇

**Comment by nthapa000** [comment]
Table 1
Fivetran: models/stg_intercom__admin.sql
Airbyte : models/source/admins.yaml

| **Fivetran Column Name** | **Corresponding Airbyte Column Name** |
|--------------------------|---------------------------------------|
| id                       | id                                    |
| name                     | name                                  |
| job_title                | job_title                             |

Table 2
Fivetran: models/stg_intercom__company_history.sql
Airbyte : models/source/companies.yaml

| **Fivetran Column Name** | **Corresponding Airbyte Column Name**          |
|--------------------------|------------------------------------------------|
| id as company_id         | id / company_id (verify)                       |
| name                     | name                                           |
| website                  | website                                        |
| industry                 | industry                                       |
| created_at               | created_at                                     |
| updated_at               | updated_at                                     |
| user_count               | user_count                                     |
| session_count            | session_count                                  |
| monthly_spend            | monthly_spend                                  |
| plan_id                  | plan.id                          |
| plan_name                | plan.name                           |

Table 3
Fivetran: models/stg_intercom__company_tag_history.sql
Airbyte : models/source/companies.yaml

| **Fivetran Column Name**       | **Corresponding Airbyte Column Name**          |
|--------------------------------|------------------------------------------------|
| company_id                     | company_id                                     |
| company_updated_at             | updated_at                                     |
| tag_id                         | tags (Array of IDs, verify)                    |

Table 4
Fivetran : models/stg_intercom__contact_company_history.sql
Airbyte : MAYBE models/source/companies.yaml (NOTHING RELEVANT)
                              contacts.yaml
Table 5
Fivetran: models/stg_intercom__contact_history.sql
Airbyte : models/source/contacts.yaml

| **Fivetran Column Name**          | **Corresponding Airbyte Column Name**          |
|-----------------------------------|------------------------------------------------|
| id as contact_id                  | id                                             |
| admin_id                          | owner_id                                       |
| created_at                        | created_at                                     |
| updated_at                        | updated_at                                     |
| signed_up_at                      | signed_up_at                                   |
| name as contact_name              | name                                           |
| role as contact_role              | role                                           |
| email as contact_email            | email                                          |
| last_replied_at                   | last_replied_at                                |
| last_email_clicked_at             | last_email_clicked_at                          |
| last_email_opened_at              | last_email_opened_at                           |
| last_contacted_at                 | last_contacted_at                              |
| unsubscribed_from_emails as is_unsubscribed_from_emails | unsubscribed_from_emails      |

Table 6
Fivetran: models/stg_intercom__contact_tag_history.sql
Airbyte : models/source/contacts.yaml

| **Fivetran Column Name**          | **Corresponding Airbyte Column Name**          |
|-----------------------------------|------------------------------------------------|
| contact_id                        | id                                             |
| contact_updated_at                | updated_at                                     |
| tag_id                            | tags (Array of IDs, verify)                    |

Table 7
Fivetran: models/stg_intercom__conversation_contact_history.sql
Airbyte : models/source/conversations.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**                               |
|----------------------------------------|----------------------------------------------------------------------|
| id as conversation_id                  | id                                                                   |
| created_at                             | created_at                                                           |
| assignee_id (verify whether same)      | admin_assignee_id                                                    |
| assignee_type                          | assignee (Nested object, verify)                                      |
| conversation_rating_value              | conversation_rating.rating                                           |
| conversation_rating_remark             | conversation_rating.remark                                           |
| first_contact_reply_created_at         | first_contact_reply.created_at                                       |
| first_contact_reply_type               | first_contact_reply.type                                             |
| read as is_read                        | read                                                                 |
| source_author_id                       | source.author.id                                                     |
| source_author_type                     | source.author.type                                                   |
| source_delivered_as                    | source.delivered_as                                                  |
| source_type                            | source.type                                                          |
| source_subject                         | source.subject                                                       |
| state                                  | state                                                                |
| updated_at                             | updated_at                                                           |
| waiting_since                          | waiting_since                                                        |
| snoozed_until                          | snoozed_until                                                        |
| sla_name                               | sla_applied.sla_name                                                 |
| sla_status                             | sla_applied.sla_status                                               |

Table 8
Fivetran: models/stg_intercom__conversation_history.sql
Airbyte : models/source/conversations.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**                               |
|----------------------------------------|----------------------------------------------------------------------|
| id as conversation_id                  | id                                                                   |
| created_at                             | created_at                                                           |
| assignee_id (verify whether same)      | admin_assignee_id                                                    |
| assignee_type                          | assignee (Nested object, verify)                                      |
| conversation_rating_value              | conversation_rating.rating                                           |
| conversation_rating_remark             | conversation_rating.remark                                           |
| first_contact_reply_created_at         | first_contact_reply.created_at                                       |
| first_contact_reply_type               | first_contact_reply.type                                             |
| read as is_read                        | read                                                                 |
| source_author_id                       | source.author.id                                                     |
| source_author_type                     | source.author.type                                                   |
| source_delivered_as                    | source.delivered_as                                                  |
| source_type                            | source.type                                                          |
| source_subject                         | source.subject                                                       |
| state                                  | state                                                                |
| updated_at                             | updated_at                                                           |
| waiting_since                          | waiting_since                                                        |
| snoozed_until                          | snoozed_until                                                        |
| sla_name                               | sla_applied.sla_name                                                 |
| sla_status                             | sla_applied.sla_status                                               |

Table 9
Fivetran: models/stg_intercom__conversation_part_history.sql
Airbyte : connectors/source_intercom/models/source/conversation_parts.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**                                               |
|----------------------------------------|--------------------------------------------------------------------------------------|
| id as conversation_part_id             | id                                                                                   |
| part_type                              | part_type                                                                            |
| body                                   | body                                                                                 |
| conversation_id                        | conversation_id                                                                      |
| author_id                              | author.id                                                                           |
| author_type                            | author.type                                                                          |
| cast(created_at as timestamp)          | created_at                                                                           |
| assigned_to_id                         | assigned_to                                                                  |
| assigned_to_type                       | assigned_to.type (verify, nested object)                                             |
| cast(conversation_updated_at as timestamp) | conversation_updated_at                                                             |
| cast(updated_at as timestamp)          | updated_at                                                                           |

Table 10
Fivetran: models/stg_intercom__conversation_tag_history.sql
Airbyte : connectors/source_intercom/models/source/conversations.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**                                               |
|----------------------------------------|-------------------------------------------------------------------------------------|
| conversation_id                        | id                                                                                  |
| tag_id(seems to be pointing to something specific)                                 | tags (Nested object, contains multiple tags associated with the conversation)       |

Table 11
Fivetran: models/stg_intercom__tag.sql
Airbyte : connectors/source_intercom/models/source/tags.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**  |
|----------------------------------------|----------------------------------------|
| id as tag_id                           | id                                     |
| trim(name) as name                     | name                                   |

Table 12
Fivetran: models/stg_intercom__team.sql
Airbyte : connectors/source_intercom/models/source/teams.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**  |
|----------------------------------------|----------------------------------------|
| id as team_id                           | id                                    |
| name                    | name                                                  |

Table 13
Fivetran: models/stg_intercom__team_admin.sql
Airbyte : connectors/source_intercom/models/source/teams.yaml

| **Fivetran Column Name**               | **Corresponding Airbyte Column Name**  |
|----------------------------------------|----------------------------------------|
| admin_id(string,seems to be pointing to a specific admin)       | admin_ids(Array of userIDs)   |
| name                    | name                                                  |

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
@nthapa000 please check my commits as I included one example of what you need to do. You don't need to create the staging tables you must create tables aren't existed in Fivetran schema.
I created the example for `admin_team` table please check the `dbt_project` inside the integration test folder I added some comments of what tables you must create. Feel free to contact me if you have questions.

**Comment by marcosmarxm** [comment]
@nthapa000 did you check my review?

**Comment by nthapa000** [comment]
@marcosmarxm Yeah I went through your review. I could understand two things one is that I need to rename all the files and then there were some changes in the sql files , but I didnt understand why you removed "name" from the admin table 🤔 
Maybe Ill need to invest some more time understanding all this....or maybe can you elaborate a bit?
Thank you

**Comment by marcosmarxm** [comment]
@nthapa000 I'll try to add another example

**Comment by nthapa000** [comment]
Hey @marcosmarxm 
I now understand what you did.`
You actually created `team_admin` is for `stg_intercom__team_admin.sql `and `teams.yaml
And not  `stg_intercom__admin.sql` and `admins.yaml`
There was a confusion becuase you removed `admin_custom`  , and added `team_admin` and that was clearly visible in commit history.
Since you removed `team_admin_custom`  and added `team_admin` in the same commit it wasnt visible on the face of it!!
Sorry about this oversight!!

**Review by marcosmarxm — APPROVED** [review]
Thanks @nthapa000 !!!

**Pull request merged**
