### PR TITLE
Source Klaviyo: added dbt converter

### LINKED ISSUE #17: Create dbt converter for Airbyte Klaviyo source connector
The goal of this task is to ensure the Airbyte Klaviyo connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/klaviyo/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

### PR DESCRIPTION
**Pull request by parthiv11**
closes #17

### CODE REVIEW

**Comment by parthiv11** [comment]
@marcosmarxm just want to know, am I on right track?

**Comment by marcosmarxm** [comment]
Looks promising, @parthiv11. I'll review your contribution tomorrow and get back to you.

**Comment by parthiv11** [comment]
person --> profiles' s transformation done with some unest json
event--> events' s transformation done with some unest json
metric--> metrics' s transformation done with some unest json


campaign --> campaigns with some unknow columns (probably joins with email template table)
| Source Field        | Mapped Field              |
|---------------------|---------------------------|
| `campaign_type`      | `type`                    |
| `created`            | `attributes.created_at`   |
| `email_template_id`  | `❌`                      |
| `from_email`         | `❌`                      |
| `from_name`          | `❌`                      |
| `id`                 | `id`                      |
| `name`               | `attributes.name`         |
| `send_time`          | `attributes.send_time`    |
| `sent_at`            | `❌`                      |
| `status`             | `attributes.status`       |
| `status_label`       | `❌`                      |
| `status_id`          | `❌`                      |
| `subject`            |     `❌`                |
| `updated`            | `attributes.updated_at`   |
| `archived`           | `attributes.archived`     |
| `scheduled`          | `attributes.scheduled_at` |



event--> events with some unknow columns 
| Source Field| Mapped Field|
|--------------------|--------------------------------------------------|
| variation          | included[0].relationships.flow-message-variation.data.id |
| campaign_id        | included[0].relationships.flow.campaign.id      |
| timestamp          | attr.timestamp                                   |
| flow_id            | included[0].relationships.flow.data.id          |
| flow_message_id    | included[0].relationships.flow-message.data.id  |
| id                 | id                                               |
| metric_id          | relationships.metric.data.id                    |
| person_id          | relationships.profile.data.id                   |
| type               | type                                             |
| uuid               | attr.uuid                                       |
| source_relation    | -                                                |
| klaviyo_source.remove_string_from_numeric('property_value') | ??              |

<details>
<summary>
ERD diagram
</summary>

Klaviyo ERD

</details>

**Comment by parthiv11** [comment]
> Looks promising, @parthiv11. I'll review your contribution tomorrow and get back to you.

@marcosmarxm

**Comment by marcosmarxm** [comment]
@parthiv11 let's continue without the columns and see if the model behave as expected.

**Comment by marcosmarxm** [comment]
@parthiv11 I pushed some changes. I was able to run using these models. For Klaviyo there is an small problem for staging which is different from other sources. It doesn't select a table but create [an union](https://github.com/fivetran/dbt_klaviyo_source/blob/main/models/tmp/stg_klaviyo__campaign_tmp.sql). For that reason it won't be possible to run a simple `dbt run`... command to have all done, but it is possible to run:
```shell
dbt run --models +source_klaviyo --target postgres # build tables used by Fivetran this is the Airbyte models
dbt run --models +klaviyo_source --target postgres # run Fivetran models
```
Can you move from draft to ready to review? I think there only a couple of things to be done here.

**Comment by parthiv11** [comment]
@marcosmarxm just pushed a commit , please check it out, 
and let me know, what next

**Review by marcosmarxm — APPROVED** [review]
Awesome work @parthiv11

**Comment by marcosmarxm** [comment]
I ran all tests manually for all 3 databases (postgres, snowflake and bigquery) It is working perfectly! Thanks @parthiv11

**Comment by parthiv11** [comment]
Thank you marcos, without your help I would not be able to do  early

**Pull request merged**
