### PR TITLE
Source GoogleAds : Add DBT Converter

### LINKED ISSUE #12: Create dbt converter for Airbyte Google Ads source connector
The goal of this task is to ensure the Airbyte Google Ads connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/google_ads/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

### PR DESCRIPTION
**Pull request by yachanaarora04**
Conversion files have been added successfully it should close #12

### CODE REVIEW

**Comment by yachanaarora04** [comment]
Hey @marcosmarxm 
Here is the list of tables with their respective columns !
### **Fivetran Table 1: stg_google_ads__account_history.sql**
### **Airbyte  Table  : account_performance_report**
| **Fivetran Column**                        | **Airbyte Column (In the DB)**                                    |
|--------------------------------------------|-------------------------------------------------------------------|
| id (as account_id)                     | customer.id (customer_id)                                     |
| updated_at                               | segments.date (segments_date)                                 |
| currency_code                            | customer.currency_code (customer_currency_code )              |
| auto_tagging_enabled                     | customer.auto_tagging_enabled (customer_auto_tagging_enabled) |
| time_zone                                | customer.time_zone (customer_time_zone)                       |
| descriptive_name (as account_name)     | customer.descriptive_name (customer_descriptive_name)         |

### **Fivetran Table 2: stg_google_ads__account_stats.sql**
### **Airbyte  Table  : account_performance_report**

| **Fivetran Column**                        | **Airbyte Column(In the DB)**                                           |
|--------------------------------------------|-------------------------------------------------------------------------|
| customer_id (as account_id)            | customer.id (customer_id)                                           |
| date (as date_day)                     | segments.date (segments_date)                                       |
| ad_network_type                          | segments.ad_network_type (segments_ad_network_type)                 |
| device                                   | segments.device (segments_device)                                   |
| clicks                                   | metrics.clicks (metrics_clicks)                                     |
| cost_micros (as spend)                 | metrics.cost_micros (metrics_cost_micros)                            |
| impressions                              | metrics.impressions (metrics_impressions)                           |
| conversions                              | metrics.conversions (metrics_conversions)                           |
| conversions_value                        | metrics.conversions_value (metrics_conversions_value)               |
| view_through_conversions                 | metrics.view_through_conversions (metrics_view_through_conversions) |

### **Fivetran Table 3: stg_google_ads__ad_history.sql**
### **Airbyte Table   : ad_group_ad**

| **Fivetran Column**                        | **Airbyte Column (In the DB)**                               |
|--------------------------------------------|-------------------------------------------------------------|
| ad_group_id                              | ad_group.id (ad_group_id)                               |
| id (as ad_id)                          | ad_group_ad.ad.id (ad_group_ad_ad_id)                   |
| name (as ad_name)                      | ad_group_ad.ad.name (ad_group_ad_ad_name)               |
| updated_at                               | segments.date (segments_date)                           |
| type (as ad_type)                      | ad_group_ad.ad.type (ad_group_ad_ad_type)               |
| status (as ad_status)                  | ad_group_ad.status (ad_group_ad_status)                 |
| display_url                              | ad_group_ad.ad.display_url (ad_group_ad_ad_display_url) |
| final_urls                               | ad_group_ad.ad.final_urls (ad_group_ad.ad.final_urls)   |

### **Fivetran Table 4: stg_google_ads__ad_stats.sql**

| **Fivetran Column**                        | **Airbyte Column (In the DB)**                                           | **Airbyte Table**               |
|--------------------------------------------|--------------------------------------------------------------------------|---------------------------------|
| customer_id (as account_id)            | customer.id (customer_id)                                            | account_performance_report    |
| date (as date_day)                     | segments.date (segments_date)                                        | ad_group_ad                   |
| ad_group_id                              | ad_group.id (ad_group_id)                                            | ad_group_ad                   |
| keyword_ad_group_criterion               | X Not Present                                                          | X Not Present                 |
| ad_network_type                          | segments.ad_network_type (segments_ad_network_type)                  | account_performance_report    |
| device                                   | ad_group_ad.ad.device_preference (ad_group_ad_ad_device_preference)  | ad_group_ad                   |
| ad_id                                    | ad_group_ad.ad.id (ad_group_ad_ad_id)                                | ad_group_ad                   |
| campaign_id                              | campaign.id (campaign.id)                                            | ad_group                      |
| clicks                                   | ad_group_ad.ad.metrics.clicks                                          | account_performance_report    |
| cost_micros (as spend)                 | ad_group_ad.ad.metrics.cost_micros                                     | account_performance_report    |
| impressions                              | ad_group_ad.ad.metrics.impressions                                     | account_performance_report    |
| conversions                              | ad_group_ad.ad.metrics.conversions                                     | account_performance_report    |
| conversions_value                        | ad_group_ad.ad.metrics.conversions_value                               | account_performance_report    |
| view_through_conversions                 | ad_group_ad.ad.metrics.view_through_conversions                        | account_performance_report    |

### **Fivetran Table 5: stg_google_ads__campaign_history.sql**

| **Fivetran Column**                        | **Airbyte Column (In the DB)**                                                    | **Airbyte Table**               |
|--------------------------------------------|---------------------------------------------------|-----------------------------------------------------------------|
| id (as campaign_id)                    | campaign.id (campaign_id)                                                     | campaign                      |
| updated_at                               | segments.date (segments_date)                                                 | campaign                      |
| name (as campaign_name)                | campaign.name (campaign_name)                                                 | campaign                      |
| customer_id (as account_id)            | customer.id  (customer_id)                                                  | account_performance_report    |
| advertising_channel_type                 | campaign.advertising_channel_type (campaign_advertising_channel_type)         | campaign                      |
| advertising_channel_subtype              | campaign.advertising_channel_sub_type (campaign_advertising_channel_sub_type) | campaign                      |
| start_date                               | campaign.start_date (campaign_start_date)                                     | campaign                      |
| end_date                                 | campaign.end_date (campaign_end_date)                                         | campaign                      |
| serving_status                           | campaign.serving_status (campaign_serving_status)                             | campaign                      |
| status                                   | campaign.status (campaign_status)                                             | campaign                      |
| tracking_url_template                    | campaign.final_url_suffix (campaign_final_url_suffix)                         | campaign                      |

### **Fivetran Table 6: stg_google_ads__campaign_stats.sql**

| **Fivetran Column**                        | **Airbyte Column     (In the DB)**                                      | **Airbyte Table**               |
|--------------------------------------------|-------------------------------------------------------------------------|---------------------------------|
| customer_id (as account_id)            | customer.id                      (customer_id)                      | account_performance_report    |
| date (as date_day)                     | segments.date                    (segments_date)                    | campaign                      |
| id (as campaign_id)                    | campaign.id                      (campaign_id)                      | campaign                      |
| ad_network_type                          | segments.ad_network_type         (segments_ad_network_type)         | account_performance_report    |
| device                                   | segments.device                  (ad_group_ad_ad_device_preference) | account_performance_report    |
| clicks                                   | metrics.clicks                   (metrics_clicks)                   | campaign                      |
| cost_micros (as spend)                 | metrics.cost_micros              (metrics_cost_micros)              | campaign                      |
| impressions                              | metrics.impressions              (metrics_impression)               | campaign                      |
| conversions                              | metrics.conversions              (metrics_conversions)              | campaign                      |
| conversions_value                        | metrics.conversions_value        (metrics_conversions_value)        | campaign                      |
| view_through_conversions                 | metrics.view_through_conversions (metrics_view_through_conversions) | display_keyword_view          |

### **Fivetran Table 7: stg_google_ads__ad_group_criterion_history.sql**

| **Fivetran Column**                        | **Airbyte Column  (In the DB)**                                                    | **Airbyte Table**               |
|--------------------------------------------|------------------------------------------------------------------------------------|---------------------------------|
| id (as criterion_id)                   | ad_group_criterion.criterion_id (ad_group_criterion_criterion_id)              | ad_group_criterion            |
| ad_group_id                              | ad_group.id (ad_group_id)                                                      | ad_group_criterion            |
| base_campaign_id                         | campaign.base_campaign(campaign_base_campaign)                                 | display_keyword_view                           |
| updated_at                               | change_status.last_change_date_time (change_status_last_change_date_time)      | ad_group_criterion            |
| type                                     | ad_group_criterion.type (ad_group_criterion_type)                              | ad_group_criterion            |
| status                                   | ad_group_criterion.status (ad_group_criterion_status)                          | ad_group_criterion            |
| keyword_match_type                       | ad_group_criterion.keyword.match_type (ad_group_criterion_keyword_match_type)  | ad_group_criterion            |
| keyword_text                             | ad_group_criterion.keyword.text (ad_group_criterion_keyword_text)              | ad_group_criterion            |

### **Fivetran Table 8: stg_google_ads__ad_group_history.sql**

| **Fivetran Column**                        | **Airbyte Column**                            | **Airbyte Table**               |
|--------------------------------------------|-----------------------------------------------|---------------------------------|
| id (as ad_group_id)                    | ad_group.id     (ad_group_id)             | ad_group                      |
| updated_at                               | segments.date   (segments_date)           | ad_group                      |
| type (as ad_group_type)                | ad_group.type   (ad_group_type)           | ad_group                      |
| campaign_id                              | campaign.id     (campaign_id)             | ad_group                      |
| campaign_name                            | campaign.name   (campaign_name)           | campaign                      |
| name (as ad_group_name)                | ad_group.name   (ad_group_name)           | ad_group                      |
| status (as ad_group_status)            | ad_group.status (ad_group_status)         | ad_group                      |

### **Fivetran Table 9: stg_google_ads__ad_group_stats.sql**

| **Fivetran Column**                        | **Airbyte Column**                                                       | **Airbyte Table**               |
|--------------------------------------------|--------------------------------------------------------------------------|---------------------------------|
| customer_id (as account_id)            | customer.id                      (customer_id)                       | account_performance_report    |
| date (as date_day)                     | segments.date                    (segments_date)                     | ad_group_ad                   |
| ad_group_id                              | ad_group.id                      (ad_group_id)                       | ad_group_ad                   |
| campaign_id                              | campaign.id                      (campaign_id)                       | ad_group                      |
| device                                   | ad_group_ad.ad.device_preference (ad_group_ad_ad_device_preference)  | ad_group_ad                   |
| ad_network_type                          | segments.ad_network_type         (segments_ad_network_type)          | account_performance_report    |
| clicks                                   | metrics.clicks                   (metrics_clicks)                    | account_performance_report    |
| cost_micros (as spend)                 | metrics.cost_micros              (metrics_cost_micros)                | account_performance_report    |
| impressions                              | metrics.impressions              (metrics_impressions)               | account_performance_report    |
| conversions                              | metrics.conversions              (metrics_conversions)               | account_performance_report    |
| conversions_value                        | metrics.conversions_value        (metrics_conversions_value)         | account_performance_report    |
| view_through_conversions                 | metrics.view_through_conversions (metrics_view_through_conversions)  | account_performance_report    |

### **Fivetran Table 10: stg_google_ads__keyword_stats.sql**
### **Airbyte Table : keyword_view**
| **Fivetran Column**                        | **Airbyte Column**                                |
|--------------------------------------------|---------------------------------------------------|
| customer_id (as account_id)            | customer.id                                     |
| date (as date_day)                     | segments.date                                   |
| ad_group_id                              | ad_group.id                                     |
| ad_group_criterion_criterion_id          | ad_group_criterion.criterion_id                 |
| campaign_id                              | campaign.id                                     |
| clicks                                   | metrics.clicks                                  |
| cost_micros (as spend)                 | metrics.cost_micros                             |
| impressions                              | metrics.impressions                             |
| conversions                              | metrics.conversions                             |
| conversions_value                        | metrics.conversions_value                       |
| view_through_conversions                 | metrics.view_through_conversions                |

**Comment by yachanaarora04** [comment]
Hey @marcosmarxm , Did you review this ? 🤔

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
One small detail with `airbyte_dbt_source_google_ads.ad_history` besides that the model is working great @yachanaarora04

**Review by marcosmarxm — APPROVED** [review]
Great contribution @yachanaarora04 !

**Comment by vikas-bansal** [comment]
@marcosmarxm @yachanaarora04 

The converter code for fivetran intermediate models is wrong. We are joining tables without any join condition resulting in a cartesian product. below are some examples - 


https://github.com/airbytehq/airbyte-dbt-models/blob/4b94f98c58aae5f5709bb009ae38d5e4f5374b00/connectors/source_google_ads/models/fivetran_converter/campaign_stats.sql#L3-L19

https://github.com/airbytehq/airbyte-dbt-models/blob/4b94f98c58aae5f5709bb009ae38d5e4f5374b00/connectors/source_google_ads/models/fivetran_converter/ad_stats.sql#L4-L24

**Comment by marcosmarxm** [comment]
@vikas-bansal can you contact me in Airbyte Slack?

**Pull request merged**
